# Generated by Django 2.1.3 on 2018-11-09 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(max_length=10, unique=True)),
                ('apellidos', models.CharField(max_length=70)),
                ('nombres', models.CharField(max_length=70)),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
    ]
