# Generated by Django 2.1.3 on 2018-11-09 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modelo', '0002_auto_20181109_1037'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estudiante',
            old_name='numMatricula',
            new_name='matricula',
        ),
    ]
